###############################################################################
#                          Generated on phpdocker.io                          #
###############################################################################
version: '3.1'
services:
  igenerator-mailhog:
    image: 'mailhog/mailhog:latest'
    container_name: igenerator-mailhog
    ports:
      - '8125:8025'

  igenerator-mysql:
    image: 'mysql:8.0'
    container_name: igenerator-mysql
    working_dir: /var/www/igenerator
    volumes:
      - ../mysql:/var/lib/mysql
      - ../mysql-files:/var/lib/mysql-files
      - ../cakephp:/var/www/igenerator
      - ./mysql/my.cnf:/etc/mysql/my.cnf
    ports:
      - '8106:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

  igenerator-nginx:
    image: 'nginx:alpine'
    container_name: igenerator-nginx
    working_dir: /var/www/igenerator
    volumes:
      - ../cakephp:/var/www/igenerator
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8180:80'
    links:
      - igenerator-php-fpm

  igenerator-php-fpm:
    build: ./php-fpm
    container_name: igenerator-php-fpm
    working_dir: /var/www/igenerator
    volumes:
      - ../cakephp:/var/www/igenerator
      - ./php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
    links:
      - igenerator-mailhog
      - igenerator-mysql
